### PR TITLE
MVP

### PR DESCRIPTION
**Pull request by NickTikhonov**
This PR brings together #18 and #15 to create a simplified version of the app that clones multiple repositories in parallel. 

### Group Cloning Assignments

The UI introduced in the mockup allows the user to view the status of multiple submissions at once. This PR connects `clone-utils` to the interface to allow for parallel cloning of submission repositories with real-time updates on progress. 

cloneall mov

This is accomplished in Redux using the `redux-thunk` Redux middleware and asynchronous action creators. [Async action creators](http://redux.js.org/docs/advanced/AsyncActions.html) break away from the "purity" of Redux, allowing it to interface with async code (such as `clone-utils.clone`).

The MVP can clone repositories of any size that [nodegit](http://www.nodegit.org/) can handle. For larger repos, it is important to notify the user of the clone progress. 

largerrepos mov

Every submission has a progress bar which gets updated at most every 300ms (enforced by a throttling helper from [UnderscoreJS](http://underscorejs.org/)). I found that updating at faster rates slows down the app, as it spends more time processing redux state updates than cloning the repository. 

### Customizable, Persistent Save Location

Users are able to change the default save location through the "Settings" menu, and on the "Confirm" screen. Settings are stored locally using `configstore`.

savelocation mov

### Cloned Assignment Directory Structure

Cloned submissions are grouped into one directory, the name of which contains the assignment title and the current date/time. Adding the latter avoids collisions if one assignment is cloned multiple times.

```console
pwd
> /tmp/Assignment 1: Introduction to Programming-08-05-2016-03-00-10
```

Repositories are named after the author's GitHub handle. 

```console
tree .
> .
├── StudentAli
│   ├── Exercises.md
│   ├── README.md
│   └── ps1.py
├── StudentEvelyn
│   ├── Exercises.md
│   ├── README.md
│   └── ps1.py
├── StudentMax
│   ├── Exercises.md
│   ├── README.md
│   └── ps1.py
├── StudentShay
│   ├── Exercises.md
│   ├── README.md
│   └── ps1.py
├── StudentZara
│   ├── Exercises.md
│   ├── README.md
│   └── ps1.py
└── StudentZi
    ├── Exercises.md
    ├── README.md
    └── ps1.py
```

### Error Handling

Errors from `clone-utils.clone` get propagated to the UI, specifically to the status string of each submission. `nodegit` doesn't seem to provide informative errors unless the clone request includes authentication secrets. For this reason, I didn't implement reporting of specific errors, instead the app reports if cloning a particular submission resulted in an error:

screen shot 2016-08-05 at 3 29 06 pm

### CODE REVIEW

**Comment by johndbritton** [comment]
This is exciting @NickTikhonov, great work.

**Comment by NickTikhonov** [comment]
Hey @johndbritton @tarebyte I think this is good to go, can you take a 👀 ? Thanks ✨

**Comment by johndbritton** [comment]
I took a look at this and ran it locally. I say :shipit: with the caveat that I'm not a super JS developer and we might want to do another more in depth review prior to shipping.

**Comment by NickTikhonov** [comment]
@johndbritton great! Hats off to @zeke, who agreed to 👀 over the codebase and give his feedback 🎉

**Pull request merged**
